import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import "./globals.css";
import { ReactQueryProvider } from "@/components/providers/ReactQueryProvider";

const nunito = Nunito({ 
	subsets: ['latin'], 
	weight: ['300', '400', '500', '600', '700'], 
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" className="scroll-smooth">
			<head>
				<meta name="viewport" content="width=device-width, initial-scale=1.0" />
			</head>
    		<body className={`${nunito.className} bg-bg text-text`}>
    			<ReactQueryProvider>
					{children}
				</ReactQueryProvider>
    		</body>
    	</html>
	);
}
